/* Base de données détaillée des Matériaux - Parralela */
/* Généré automatiquement par generate_materiaux.ps1 */
const natureDetailDB = [
    {
        name: "Argile Lunaire de Kyel",
        type: "Minéral",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent exclusivement dans une zone silencieuse du Royaume de Balmajosza, en surface, au cœur d’une plaine stérile. La zone est considérée comme une terre sacrée, dépourvue de toute autre forme de vie connue.",
        composition: "Argile minérale imprégnée de flux lunaires constants. Sa matière ne conserve ses propriétés que tant qu’elle reste exposée à son environnement d’origine.",
        aspect: "Argile pâle, à la texture lisse et froide, baignée uniquement par la lumière lunaire. Elle ne présente aucune réaction visible hors de cette illumination spécifique.",
        proprietes: ["Sensibilité exclusive à la lumière lunaire", "Stabilité conditionnelle liée au lieu", "Aucune réaction connue à d’autres sources lumineuses ou magiques"],
        utilisations: ["Modelage rituel ou structurel directement sur place"],
        nonPreciseesUtil: false,
        contraintes: ["Transport impossible : l’argile perd ses propriétés dès qu’elle quitte la zone", "Doit être modelée sur site, sans délai", "Extraction brute inutile sans mise en forme immédiate"],
        notes: "L’Argile Lunaire de Kyel impose une logique de création liée au lieu, et non à la possession du matériau. Son usage transforme la zone elle-même en atelier, rendant toute exploitation longue, méthodique et contraignante."
    },
    {
        name: "Bois",
        type: "Flore",
        classe: "Standard",
        etat: "Transformé",
        origine: "Matériau issu de végétaux communs, présent dans la majorité des régions du monde. Facilement accessible et largement exploité.",
        composition: "Matière végétale fibreuse, structurée en veines naturelles. La composition varie selon l’essence, sans modifier son usage de base.",
        aspect: "Peut être taillé, assemblé ou renforcé sans difficulté majeure.",
        proprietes: ["Réactivité à certaines magies végétales", "Sensible aux manipulations liées à Verdania", "Comportement passif hors influence magique directe"],
        utilisations: ["Construction (structures, charpentes, supports)", "Fabrication d’objets usuels", "Support de manipulation magique végétale"],
        nonPreciseesUtil: false,
        contraintes: ["Faible résistance aux charges magiques élevées", "Sensible au feu et à l’humidité", "Nécessite des traitements pour une durabilité accrue"],
        notes: "Le bois est un matériau fondamental, apprécié autant pour sa simplicité que pour sa compatibilité avec les affinités végétales, comme celle de Galen Eloiranôr, capable de le manipuler via Verdania-Radicis. Il sert souvent de base neutre avant toute spécialisation magique."
    },
    {
        name: "Coquille de Pyrocrabe Ancien",
        type: "Organique",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau provenant des côtes du Royaume d’Afordia, plus précisément de grottes marines volcaniques. Les Pyrocrabes Anciens y vivent en permanence.",
        composition: "Coquille organique épaisse, issue d’un organisme adapté à des conditions marines et volcaniques extrêmes. La structure est minéralisée par une exposition prolongée à la chaleur et aux dépôts volcaniques.",
        aspect: "Coquille massive aux teintes sombres, marquée par des stries et zones vitrifiées. Des traces de chaleur ancienne persistent dans la matière.",
        proprietes: ["Stabilité élevée liée à la minéralisation naturelle", "Aucune manifestation active connue hors de son environnement d’origine"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["La coquille ne peut être récupérée qu’après la mort naturelle du Pyrocrabe Ancien", "Toute tentative de prélèvement anticipé est impossible", "Habitat situé dans des grottes marines volcaniques, dangereuses et difficiles d’accès", "Temps d’attente imprévisible avant disponibilité du matériau"],
        notes: "La Coquille de Pyrocrabe Ancien impose une logique d’attente et de respect du cycle naturel. Sa rareté ne provient pas de la créature elle-même, mais de l’impossibilité morale et pratique d’accélérer son obtention."
    },
    {
        name: "Cristal de Réfraction Binaire",
        type: "Minéral",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau exclusivement trouvé dans la Caverne aux Miroirs, un site souterrain situé sous Paidju. Aucune occurrence connue hors de cet environnement.",
        composition: "Cristal minéral à structure interne double, organisée autour de plans réfléchissants naturels. Sa constitution lui permet de manipuler la lumière sans la dissiper.",
        aspect: "Cristal translucide à facettes multiples, dont la surface agit comme un miroir imparfait. Il peut soit émettre une lumière vive et agressive, soit devenir visuellement discret, se fondant presque dans son environnement.",
        proprietes: ["Réfraction active de la lumière", "Capacité de modulation lumineuse", "Passage instantané entre deux états :"],
        utilisations: ["Contrôle de la visibilité dans des environnements confinés", "Dispositifs d’aveuglement ou de perturbation visuelle", "Supports optiques magiques avancés", "Environnements nécessitant une alternance lumière / dissimulation"],
        nonPreciseesUtil: false,
        contraintes: ["Fonctionnement dépendant fortement de la lumière ambiante", "Peu efficace dans l’obscurité totale", "Fragilité structurelle si soumis à des chocs répétés"],
        notes: "La nature binaire du cristal est directement liée à l’environnement de la Caverne aux Miroirs, où la lumière est constamment fragmentée et renvoyée. Son comportement ne montre aucune évolution adaptative connue."
    },
    {
        name: "Cuivre",
        type: "Minéral",
        classe: "Standard",
        etat: "Transformé",
        origine: "Métal courant, présent à de nombreux endroits du monde et facilement accessible. Aucune zone d’extraction spécifique connue ou restreinte.",
        composition: "Métal malléable à forte conductivité. Sa structure permet une circulation fluide des flux énergétiques.",
        aspect: "Métal à la teinte rouge-orangé caractéristique. Sa surface peut être polie ou travaillée sans altérer ses propriétés conductrices.",
        proprietes: ["Excellente conductivité magique", "Transmission stable du mana", "Faible résistance aux flux prolongés"],
        utilisations: ["Fabrication de bagues", "Fils de liaison pour circuits magiques", "Structures de base d’objets magiques", "Support non actif pour enchantements"],
        nonPreciseesUtil: false,
        contraintes: ["Peu résistant aux charges magiques élevées", "Ne stocke pas le mana", "Doit être combiné à d’autres matériaux pour des usages avancés"],
        notes: "Le cuivre constitue la base structurelle de nombreux objets magiques. Il n’est pas recherché pour sa puissance, mais pour sa fiabilité et sa capacité à servir de lien entre différents composants."
    },
    {
        name: "Écaille de Vombre",
        type: "Organique",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent dans un souterrain éthéré situé sous le Royaume de Balmaosza, une zone instable connue pour être la seule où apparaissent des créatures dites « entre-deux-mondes ».",
        composition: "Écaille organique issue d’une créature appelée Vombre. La matière semble partiellement ancrée hors du plan physique stable.",
        aspect: "Écaille sombre aux reflets changeants, dont les contours paraissent parfois flous ou décalés. Son apparence varie légèrement selon l’angle d’observation.",
        proprietes: ["Résonance avec des états intermédiaires de réalité", "Comportement instable hors de sa zone d’origine", "Aucune réaction documentée sans interaction directe avec un Vombre"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Rencontre obligatoire avec un Vombre vivant", "L’écaille doit être donnée volontairement par la créature", "Impossible à obtenir par extraction, chasse ou récupération indirecte", "Zone d’accès instable et imprévisible"],
        notes: "L’Écaille de Vombre repose sur une logique de consentement et de présence, non de domination ou de prélèvement. Son obtention implique une interaction directe avec une entité appartenant à un état d’existence intermédiaire."
    },
    {
        name: "Écorce d'Ignoronce",
        type: "Flore",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau issu d’un arbre rare poussant en surface dans une zone volcanique du Royaume d’Afordia, à proximité immédiate d’une rivière de feu. Aucune autre zone d’apparition connue.",
        composition: "Écorce végétale épaisse, adaptée à des températures extrêmes. La matière conserve ses propriétés tant qu’elle n’est pas séparée brutalement de son environnement.",
        aspect: "Écorce sombre et rugueuse, marquée par des veinures chauffées en profondeur. Elle ne brûle pas malgré une exposition continue à la chaleur volcanique.",
        proprietes: ["Tolérance élevée à la chaleur", "Stabilité en environnement thermique extrême", "Aucune réaction connue hors de ces conditions"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Arbre très difficile à approcher", "Implantation au bord d’une rivière de feu", "Zone gardée par une faune thermorésistante", "Extraction risquée malgré l’absence de protection rituelle ou politique"],
        notes: "L’Écorce d’Ignoronce est un matériau rare dont la difficulté réside dans l’approche physique et la survie dans un environnement hostile, plutôt que dans une contrainte symbolique ou magique."
    },
    {
        name: "Épine de Murmurocéan",
        type: "Organique",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau issu d’une créature abyssale vivant dans les profondeurs marines sous l’Empire Coudrezian, dans un environnement souterrain marin. La créature ne remonte jamais à la surface.",
        composition: "Épine organique provenant d’un organisme adapté aux abysses. Sa structure est conçue pour résister à des conditions de pression extrêmes.",
        aspect: "Épine dense et allongée, d’apparence sombre. Elle conserve des traces de l’environnement abyssal, sans manifestation lumineuse connue à l’air libre.",
        proprietes: ["Instabilité du mana environnant dans sa zone d’origine", "Aucune réaction documentée hors des abysses"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Accès uniquement par plongée abyssale", "Danger extrême lié à :", "Extraction impossible sans exposition prolongée à un environnement mortel"],
        notes: "L’Épine de Murmurocéan est un matériau dont la difficulté ne réside pas dans sa manipulation, mais dans l’atteinte même de sa source. Toute tentative d’obtention implique une confrontation directe avec l’écosystème abyssal."
    },
    {
        name: "Fibre de Lueur Suspendue",
        type: "Flore",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent sous une île forestière flottante située dans le Grand-Duché de Harmouth. Aucune autre zone d’apparition connue.",
        composition: "Fibre végétale lumineuse, suspendue naturellement sous la masse terrestre de l’île. Sa structure est sensible aux flux magiques environnants.",
        aspect: "Ensemble de fibres fines émettant une lueur douce, visibles principalement lorsqu’elles sont en suspension libre. La luminosité réagit aux variations du mana ambiant.",
        proprietes: ["Réaction directe aux perturbations de mana", "Sensibilité accrue aux émissions magiques externes", "Comportement instable en présence de flux artificiels"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Toute approche utilisant une aide magique externe perturbe la fibre", "Nécessite une approche en vol sans assistance magique", "Récolte rendue complexe par la position et la sensibilité du matériau"],
        notes: "La contrainte d’approche impose une maîtrise physique ou naturelle du vol, excluant toute assistance magique directe. Cette particularité fait de la Fibre de Lueur Suspendue un matériau difficile d’accès, même pour des utilisateurs expérimentés."
    },
    {
        name: "Fil de Spectre Silencieux",
        type: "Organique",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau présent sur une île volante spectrale située à proximité de la Théocratie de Vétolilian. L’accès à l’île n’est possible que dans des conditions très spécifiques.",
        composition: "Fil d’origine spectrale, issu d’entités immatérielles appelées spectres. La matière ne se manifeste pleinement que lors de leur apparition.",
        aspect: "Fil extrêmement fin, presque invisible, semblant flotter sans support. Il ne produit ni son, ni vibration perceptible.",
        proprietes: ["Manifestation conditionnée au mana pur", "Absence totale de réaction sans appel énergétique approprié", "Comportement passif hors apparition spectrale"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Accès uniquement via une zone de distorsion magique nocturne", "Les spectres n’apparaissent que par l’appel du mana pur", "Impossible d’obtenir le matériau sans déclencher volontairement cette apparition", "Fenêtre d’accès limitée et instable"],
        notes: "Le Fil de Spectre Silencieux ne peut être récolté que dans un état précis du monde, lorsque la frontière entre le matériel et l’immatériel s’amincit. Toute tentative hors de ce contexte est vouée à l’échec."
    },
    {
        name: "Fragment de Miroir de Solstice",
        type: "Minéral",
        classe: "Épique",
        etat: "Préservé",
        origine: "Fragment conservé au sein des temples célestes de la Théocratie de Vétolilan. Aucune occurrence connue hors de ces lieux sacrés.",
        composition: "Fragment minéral à surface réfléchissante parfaitement lisse, issu d’un miroir sacré ancien. La structure exacte du miroir d’origine n’est pas documentée.",
        aspect: "Éclat translucide et lumineux, dont la surface agit comme un miroir pur. La réflexion produite semble plus liée à la lumière ambiante qu’à la matière elle-même.",
        proprietes: ["Résonance avec les flux lumineux", "Réaction aux signatures magiques", "Inertie totale en l’absence de reconnaissance magique"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Matériau très bien gardé dans un temple de lumière", "Accès strictement conditionné à une reconnaissance magique", "Impossible à approcher ou manipuler sans validation magique préalable"],
        notes: "Le Fragment de Miroir de Solstice n’est pas protégé par des moyens physiques classiques, mais par une logique de sélection magique. La reconnaissance requise agit comme un filtre, rendant toute tentative brute ou détournée inefficace."
    },
    {
        name: "Fragment du Miroir du Néant",
        type: "Minéral",
        classe: "Rare",
        etat: "Altéré",
        origine: "Matériau présent dans une cavité maudite, zone corrompue située dans les souterrains. Aucune occurrence connue hors de ces zones affectées par le Néant.",
        composition: "Fragment minéral à surface réfléchissante instable, issu d’un miroir ancien lié au Néant. La matière semble partiellement déconnectée des lois physiques classiques.",
        aspect: "Surface sombre et réfléchissante, renvoyant une image inversée de la réalité. La réflexion ne correspond pas fidèlement à l’objet observé, mais à son envers.",
        proprietes: ["Résonance exclusive avec les énergies du Néant", "Aucune interaction avec les affinités non liées au Néant", "Comportement inerte hors zone corrompue"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Extraction impossible sans une affinité liée au Néant", "Zone d’origine corrompue et instable", "Toute tentative d’extraction par un autre biais échoue"],
        notes: "Le Fragment du Miroir du Néant n’oppose pas une résistance physique, mais une sélection énergétique absolue. Il ne peut être séparé de son environnement que par une affinité capable d’interagir directement avec le Néant."
    },
    {
        name: "Griffe de Kérugan",
        type: "Organique",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau prélevé sur un Kérugan, créature massive vivant dans les mines de Kaiyurt, territoire du Beylik de Kaiyurt. Aucune autre zone d’apparition connue.",
        composition: "Griffe organique extrêmement dense, issue d’un organisme à carapace minéralisée et imprégnée de lave. La matière combine des structures biologiques et des dépôts volcaniques solidifiés.",
        aspect: "Griffe sombre, lourde, parcourue de fissures incandescentes rappelant la lave en circulation sous une carapace noire. La chaleur est perceptible à proximité immédiate.",
        proprietes: ["Résonance avec des environnements volcaniques", "Stabilité maintenue tant que la structure n’est pas fragmentée"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Nécessite un affrontement direct avec un Kérugan", "Créature protégée par une carapace massive et brûlante", "Environnement minier hostile, chaleur et instabilité constantes", "Prélèvement impossible sans neutralisation préalable de la créature"],
        notes: "La Griffe de Kérugan est un matériau dont la difficulté d’obtention repose sur la résistance extrême de la créature et la dangerosité de son habitat. La présence de lave intégrée à son corps rend toute tentative de récupération particulièrement risquée."
    },
    {
        name: "Griffes et Dents de Drakyns",
        type: "Organique",
        classe: "Peu commun",
        etat: "Naturel",
        origine: "Matériaux récupérés sur les petits drakyns, des lézards magiques vivant dans la Gorge de Halmoor. La présence de ces créatures est localisée à cet environnement rocheux.",
        composition: "Structures organiques dures issues de créatures magiques reptiliennes. La matière conserve une densité supérieure à celle d’animaux non magiques.",
        aspect: "Griffes et dents de taille modérée, aux teintes sombres. Les surfaces sont naturellement affûtées et résistantes à l’usure.",
        proprietes: ["Résistance accrue liée à l’origine magique", "Comportement passif hors de la créature", "Aucune manifestation active connue"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Nécessite une interaction directe avec des drakyns", "Créatures mobiles et agressives, mais de petite taille", "Récupération possible après neutralisation ou récupération post-mortem"],
        notes: "Les Griffes et Dents de Drakyns constituent une ressource organique eu commune, recherchée pour leur robustesse naturelle. Leur obtention reste dangereuse, mais accessible à des groupes préparés connaissant bien la Gorge de Halmoor."
    },
    {
        name: "L'Œil de Cyclone Silencieux",
        type: "Minéral",
        classe: "Épique",
        etat: "Manifesté",
        origine: "Matériau situé au cœur d’un cyclone d’eau invoqué sur une île du Grand-Duché de Harmouth. Il n’existe que tant que le phénomène est maintenu.",
        composition: "Orbe d’air comprimé, parfaitement contenue et enserrée par de l’eau statique. La structure repose sur un équilibre instable entre pression interne et confinement hydrique.",
        aspect: "Sphère translucide immobile, suspendue au centre du cyclone. Malgré la violence environnante, l’orbe elle-même est totalement silencieuse, sans turbulence visible.",
        proprietes: ["Maintien d’un équilibre pression / confinement", "Inertie interne malgré un environnement chaotique", "Dissipation immédiate en cas de rupture du cyclone"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Localisation au cœur d’un cyclone d’eau actif", "Accès soumis à des forces extrêmes et instables", "Disparition du matériau si le phénomène cesse", "Récupération nécessitant une intervention directe au point le plus dangereux"],
        notes: "L’Œil de Cyclone Silencieux n’est pas un matériau dormant, mais un état condensé de forces élémentaires. Sa valeur tient à l’instant précis et à la maîtrise requise pour l’atteindre sans briser son équilibre."
    },
    {
        name: "Laiton",
        type: "Minéral",
        classe: "Standard",
        etat: "Transformé",
        origine: "Alliage courant, largement disponible et facile à travailler. Utilisé sans restriction géographique notable.",
        composition: "Alliage métallique à base de cuivre, conçu pour offrir un bon compromis entre malléabilité et tenue mécanique.",
        aspect: "Métal jaune doré, à l’aspect brillant une fois poli. Conserve une apparence stable dans le temps lorsqu’il est entretenu.",
        proprietes: ["Conductivité magique correcte", "Réaction neutre au mana", "Ne stocke pas l’énergie"],
        utilisations: ["Fabrication de bagues de différentes tailles", "Supports simples pour objets ou accessoires magiques légers"],
        nonPreciseesUtil: false,
        contraintes: ["Moins conducteur que le cuivre", "Peu adapté aux charges magiques élevées", "Usage limité à des fonctions structurelles ou décoratives"],
        notes: "Le laiton est apprécié pour sa souplesse de mise en forme, permettant la fabrication rapide de bagues standardisées. Il sert principalement de matériau utilitaire, sans vocation énergétique avancée."
    },
    {
        name: "Nerf de Liane-Flamme",
        type: "Flore",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent dans une jungle souterraine située sous la Théocratie de Vétolilian. L’environnement est dense, humide et dominé par une végétation agressive.",
        composition: "Fibre végétale interne issue d’une plante semi-vivante. La structure reste active tant que la plante n’est pas neutralisée.",
        aspect: "Liane épaisse parcourue de zones incandescentes. La plante réagit immédiatement à toute proximité, déclenchant des mouvements brusques et des brûlures de contact.",
        proprietes: ["Activité thermique constante", "Réaction agressive aux perturbations physiques", "Aucune manifestation connue une fois la plante neutralisée"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Plante hostile, attaquant tout ce qui approche", "Extraction possible uniquement sans brûlure du nerf", "Requiert une neutralisation tactique, mais jugée facile avec la méthode adéquate"],
        notes: "Le Nerf de Liane-Flamme est dangereux par réflexe, non par complexité. Sa classification Rare repose sur un risque maîtrisable, la difficulté tenant davantage à la précision de l’intervention qu’à l’accès ou au temps."
    },
    {
        name: "Parralith",
        type: "Minéral",
        classe: "Standard",
        etat: "Naturel",
        origine: "Minerai présent majoritairement dans les environnements souterrains, réparti à l’échelle mondiale. Il peut également apparaître à la surface, mais de manière plus rare et dispersée.",
        composition: "Pierre minérale composée de Parralum (Pm), élément périodique propre au monde de Parralela. Le Parralum agit comme un conducteur et un accumulateur naturel de mana.",
        aspect: "Roche dense, veinée de noir, émettant une lueur bleue pulsante, régulière, évoquant un rythme respiratoire. Cette pulsation s’intensifie en présence de mana actif.",
        proprietes: ["Capacité naturelle de stockage du mana", "Diffusion stable et continue", "Réaction passive au mana ambiant", "Faible perte énergétique sur la durée"],
        utilisations: ["Réservoirs de mana externes", "Systèmes d’éclairage urbain", "Infrastructure magique standard", "Support énergétique non offensif"],
        nonPreciseesUtil: false,
        contraintes: ["Rendement limité comparé aux matériaux rares", "Nécessite un volume conséquent pour des usages intensifs", "Peu efficace pour des applications de haute puissance"],
        notes: "Matériau fondamental du développement magique civil. Sa stabilité et sa disponibilité en font la base de nombreuses infrastructures, notamment dans les cités et zones densément peuplées."
    },
    {
        name: "Parralith Pure",
        type: "Minéral",
        classe: "Unique",
        etat: "Naturel (altéré par exposition environnementale)",
        origine: "Matériau d’origine extra-planétaire provenant de la lune brisée Manelis. Arrivé sur Parralela sous forme de météores lors de la Grande Rupture. Présence extrêmement rare, limitée aux sites d’impact identifiés ou à des fragments isolés.",
        composition: "Forme hautement concentrée de Parralum (Pm) à l’état pur. La structure interne est instable et réactive, incapable de rester totalement figée dans une configuration unique.",
        aspect: "Cristal minéral à l’éclat bleu intense, parcouru de pulsations irrégulières. Sa luminosité, sa teinte et son comportement varient en fonction de l’environnement magique dans lequel il se trouve. La pierre donne l’impression d’observer ou de réagir, malgré son origine minérale.",
        proprietes: ["Puissance énergétique extrêmement élevée", "Instabilité naturelle permanente", "Capacité d’adaptation environnementale", "Développement d’une affinité magique propre, à la manière d’un être vivant", "Résonance évolutive au mana ambiant"],
        utilisations: ["Ingrédient fondamental et indispensable à la forge de toute Arme Unique", "Catalyseur de lien entre l’arme et son porteur", "Support de synchronisation magique avancée"],
        nonPreciseesUtil: false,
        contraintes: ["Rareté extrême", "Instabilité dangereuse hors environnement contrôlé", "Impossible à substituer pour la création d’une Arme Unique", "Nécessite une compatibilité précise avec son porteur ou son contexte d’intégration"],
        notes: "Un fragment de Parralith Pure est logé dans le cœur de Lily, constituant un cas sans précédent connu. Ce matériau marque une rupture fondamentale entre la matière inerte et la logique du vivant, brouillant volontairement la frontière entre minéral et affinité."
    },
    {
        name: "Pierre de Noxive",
        type: "Minéral",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau présent dans le désert noir de l’Empire Coudrezian. La zone est connue, mais strictement contrôlée.",
        composition: "Pierre minérale sombre, dense, d’origine terrestre. Aucune transformation connue à l’état naturel.",
        aspect: "Pierre noire aux reflets mats, absorbant visuellement la lumière ambiante. Son apparence discrète contraste avec la valeur qui lui est attribuée.",
        proprietes: [],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Matériau très convoité", "Extraction illégale", "Zones et stocks contrôlés par des groupes puissants", "Toute tentative d’obtention implique :"],
        notes: "La dangerosité de la Pierre de Noxive ne provient pas de sa nature, mais de son statut politique et criminel. Sa possession ou sa recherche expose directement à des réseaux d’influence et de représailles."
    },
    {
        name: "Plume d'Hermivol",
        type: "Organique",
        classe: "Épique",
        etat: "Naturel",
        origine: "Matériau provenant d’une île volante lumineuse située au-dessus de la Principauté d'Unter. La plume est liée à l’apparition de l’oiseau Hermivol, une créature extrêmement rare.",
        composition: "Plume organique issue d’un être vivant ailé. Aucune transformation ou altération connue à l’état naturel.",
        aspect: "Plume légère à l’éclat lumineux naturel. Son apparence est associée à la lumière ambiante et à l’altitude de son environnement d’origine.",
        proprietes: [],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["L’oiseau Hermivol n’apparaît qu’au lever parfait des deux lunes", "La plume ne peut pas être obtenue par la chasse", "Elle tombe naturellement à un moment précis, impossible à forcer", "Toute tentative de prélèvement actif est exclue"],
        notes: "La Plume d’Hermivol repose sur une logique d’attente et de synchronisation, et non d’intervention. Son obtention dépend entièrement du respect du moment et des conditions d’apparition de la créature."
    },
    {
        name: "Poudre d'Obsidambre",
        type: "Minéral",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent à la surface de zones chaotiques de l’Empire Kaunioémien. Les cristaux à l’origine de la poudre se forment dans des poches de cendres mouvantes, dont l’emplacement n’est jamais totalement stable.",
        composition: "Résidu minéral issu de cristaux d’Obsidambre fragmentés. La matière est intimement liée à des dépôts volcaniques instables.",
        aspect: "Poudre sombre aux reflets ambrés discrets. Les particules semblent légèrement scintiller lorsqu’elles sont exposées à des variations de l’environnement magique.",
        proprietes: ["Interaction passive avec la magie ambiante", "Sensibilité aux fluctuations magiques de la région", "Aucun comportement actif documenté hors de son milieu d’origine"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Région instable et imprévisible", "Cristaux formés dans des cendres mouvantes", "Accès limité par la magie environnante", "Récolte dépendante des conditions locales au moment de l’exploration"],
        notes: "La Poudre d’Obsidambre est un matériau rare dont la difficulté tient à l’instabilité permanente du terrain et à l’influence de la magie ambiante, rendant toute extraction incertaine et temporaire."
    },
    {
        name: "Poussière de Lune Obscure",
        type: "Minéral",
        classe: "Rare",
        etat: "Préservé",
        origine: "Matériau conservé au sein d’un monastère du Saint-État de Vialedo, à la surface. La poussière est tombée lors d’un ancien solstice et n’existe plus à l’état naturel connu.",
        composition: "Poussière minérale fine d’origine lunaire. La matière est stable tant qu’elle reste préservée dans son contenant.",
        aspect: "Poudre sombre aux reflets mats, semblant absorber légèrement la lumière ambiante. Aucune manifestation visible hors manipulation contrôlée.",
        proprietes: ["Résonance lunaire résiduelle", "Inertie apparente en dehors de conditions rituelles connues"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Matériau protégé dans un monastère", "Accès conditionné à une négociation ou une infiltration subtile", "Extraction brute impossible sans violer l’autorité religieuse"],
        notes: "La Poussière de Lune Obscure est moins dangereuse par sa nature que par son statut sacré. Toute tentative d’obtention engage des conséquences politiques et religieuses directes."
    },
    {
        name: "Sang Solidifié de Salamandre Dorée",
        type: "Organique",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau issu d’une salamandre dorée vivant sur une île volante volcanique située au-dessus du Grand-Duché de Harmouth. Aucune autre zone d’apparition connue.",
        composition: "Sang organique ayant subi une solidification naturelle lors d’un processus biologique spécifique. La matière conserve une structure dense malgré son origine liquide.",
        aspect: "Substance solidifiée à l’éclat doré, présentant une surface lisse et compacte. La teinte rappelle une matière chauffée, sans écoulement visible.",
        proprietes: ["Aucune manifestation connue hors du contexte biologique de la créature", "Stabilité liée à l’état solidifié"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["La salamandre n’apparaît qu’en phase de mue", "Fenêtre d’obtention très limitée dans le temps", "Extraction extrêmement délicate, incompatible avec toute approche brutale", "Environnement volcanique et aérien, difficile d’accès"],
        notes: "Le Sang Solidifié de Salamandre Dorée ne peut être obtenu ni par la chasse classique, ni par un prélèvement forcé. Son existence même dépend d’un instant biologique précis, rendant toute tentative d’anticipation incertaine."
    },
    {
        name: "Sève figée de Brume d'Âme",
        type: "Flore",
        classe: "Rare",
        etat: "Naturel",
        origine: "Matériau présent dans des grottes végétales sacrées, situées en souterrain humide sous le Royaume de Karostos. Aucune occurrence connue hors de ces cavités.",
        composition: "Sève végétale ancienne, progressivement figée par des conditions spirituelles et environnementales spécifiques. La matière conserve une structure organique malgré son état solidifié.",
        aspect: "Substance figée à l’aspect semi-cristallin, enveloppée d’une brume diffuse persistante. La sève semble immobile, mais jamais totalement inerte.",
        proprietes: ["Résonance avec des flux spirituels", "Stabilité liée au maintien du rituel", "Absence de réaction connue hors de la zone sacrée"],
        utilisations: [],
        nonPreciseesUtil: true,
        contraintes: ["Extraction très lente, impossible à accélérer", "Nécessite patience et rituel", "Zone gardée par un esprit ancien", "Toute tentative non rituelle est exclue"],
        notes: "La Sève figée de Brume d’Âme ne se prélève pas par force ou opportunisme. Son obtention repose sur le respect du lieu, du temps et de la présence spirituelle qui en assure la garde."
    }
];